---
name: development
kind: pipeline
type: docker

trigger:
  branch:
    - master
  event:
    - push

concurrency:
  limit: 1

environment:
  MIX_ENV: prod

steps:
  - name: npm assets
    image: node:lts # we're using standard version because git is needed
    volumes:
    - name: npm-temp
      path: /root/.npm
    commands:
    - cd assets
    - npm install
    - npm run build

  # - name: download assets
  #   image: minio/mc
  #   environment:
  #     MC_HOST_minio:
  #       from_secret: minio_connection
  #   commands:
  #   - mc cp --recursive minio/phoenix_svelte_adminlte-assets/ /drone/src/apps/priv/static

  - name: elixir deps
    image: elixir:1.12-alpine
    volumes:
      - name: mix-temp
        path: /root/.mix
    commands:
    - mix do local.hex --force, local.rebar --force
    - mix do deps.get --only $MIX_ENV, deps.compile

  - name: digest
    depends_on:
    - elixir deps
    - npm assets
    image: elixir:1.12-alpine
    volumes:
      - name: mix-temp
        path: /root/.mix
    commands:
    - mix phx.digest

  - name: assemble release
    depends_on:
    - digest
    image: elixir:1.12-alpine
    volumes:
      - name: mix-temp
        path: /root/.mix
    commands:
    - mix release

  - name: dockerfile build
    depends_on:
      - assemble release
    image: plugins/docker
    settings:
      repo: registry.km8.es/phoenix-svelte-adminlte
      tags:
        - "dev"
      registry: registry.km8.es
      username:
        from_secret: docker_repo_user
      password:
        from_secret: docker_repo_password
      build_args:
        - MIX_ENV=prod

  - name: deploy
    image: appleboy/drone-ssh
    depends_on:
      - dockerfile build
    settings:
      host: 10.0.0.9
      port: 22
      username:
        from_secret: web-01_ssh_user
      key:
        from_secret: web-01_ssh_key
      passphrase:
        from_secret: web-01_ssh_passphrase
      script:
        - cd /srv/docker/phoenix-svelte-adminlte-dev
        - docker-compose down
        - docker-compose pull
        - docker-compose up -d

volumes:
  - name: mix-temp
    temp: {}
  - name: npm-temp
    temp: {}